// <auto-generated />
using System;
using Hikru.Position.Backend.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hikru.Position.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725055107_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hikru.Position.Backend.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a11111-aaaa-4111-aaaa-1111a1a1a1a1"),
                            Description = "Responsible for software development, architecture and technical innovation.",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("b2b22222-bbbb-4222-bbbb-2222b2b2b2b2"),
                            Description = "Handles branding, digital campaigns, and market research.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("c3c33333-cccc-4333-cccc-3333c3c3c3c3"),
                            Description = "Manages client relationships and drives revenue growth.",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("d4d44444-dddd-4444-dddd-4444d4d4d4d4"),
                            Description = "Oversees recruitment, employee well-being and internal policies.",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("e5e55555-eeee-4555-eeee-5555e5e5e5e5"),
                            Description = "Controls budgeting, accounting, and financial reporting.",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("f6f66666-ffff-4666-ffff-6666f6f6f6f6"),
                            Description = "Leads product vision, roadmap and customer experience.",
                            Name = "Product"
                        },
                        new
                        {
                            Id = new Guid("a9a99999-a9a9-4999-a9a9-9999a9a9a9a9"),
                            Description = "Supports clients post-sale and ensures their satisfaction and retention.",
                            Name = "Customer Success"
                        });
                });

            modelBuilder.Entity("Hikru.Position.Backend.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-aaaa-4aaa-aaaa-aaaaaaaaaaaa"),
                            Budget = 110000.0,
                            ClosingDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("a1a11111-aaaa-4111-aaaa-1111a1a1a1a1"),
                            Description = "Responsable del desarrollo de servicios backend usando .NET 8 y Azure Functions.",
                            Location = "Lima, Perú",
                            RecruiterId = new Guid("a1e0a0f3-11a2-4eaa-8bfb-1b4b1f98a111"),
                            Status = 1,
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            Id = new Guid("20202020-bbbb-4bbb-bbbb-bbbbbbbbbbbb"),
                            Budget = 85000.0,
                            ClosingDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("f6f66666-ffff-4666-ffff-6666f6f6f6f6"),
                            Description = "Diseño de interfaces centradas en el usuario para la nueva plataforma SaaS.",
                            Location = "Remoto - LatAm",
                            RecruiterId = new Guid("b2c1b1e4-22b3-4fbb-9cfc-2c5c2f09b222"),
                            Status = 1,
                            Title = "UX Designer"
                        },
                        new
                        {
                            Id = new Guid("30303030-cccc-4ccc-cccc-cccccccccccc"),
                            Budget = 65000.0,
                            DepartmentId = new Guid("b2b22222-bbbb-4222-bbbb-2222b2b2b2b2"),
                            Description = "Optimización de campañas en Google Ads, SEO y analítica web.",
                            Location = "Santiago, Chile",
                            RecruiterId = new Guid("c3d2c2f5-33c4-4bcc-adfd-3d6d3a10c333"),
                            Status = 0,
                            Title = "Digital Marketing Analyst"
                        },
                        new
                        {
                            Id = new Guid("40404040-dddd-4ddd-dddd-dddddddddddd"),
                            Budget = 48000.0,
                            ClosingDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("a1a11111-aaaa-4111-aaaa-1111a1a1a1a1"),
                            Description = "Desarrollo de interfaces en React y TypeScript. Ideal para primeros trabajos.",
                            Location = "Buenos Aires, Argentina",
                            RecruiterId = new Guid("b7f6f6b9-77f8-4bff-bfef-7f0f7a54b777"),
                            Status = 1,
                            Title = "Junior Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("50505050-eeee-4eee-eeee-eeeeeeeeeeee"),
                            Budget = 72000.0,
                            ClosingDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e5e55555-eeee-4555-eeee-5555e5e5e5e5"),
                            Description = "Gestión contable, conciliaciones y reportes mensuales.",
                            Location = "Lima, Perú",
                            RecruiterId = new Guid("f6f5f5a8-66f7-4aff-dfef-6f9f6a43f666"),
                            Status = 2,
                            Title = "Accounting Specialist"
                        },
                        new
                        {
                            Id = new Guid("60606060-ffff-4fff-ffff-ffffffffffff"),
                            Budget = 90000.0,
                            ClosingDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("d4d44444-dddd-4444-dddd-4444d4d4d4d4"),
                            Description = "Gestión del talento, desarrollo organizacional y clima laboral.",
                            Location = "Quito, Ecuador",
                            RecruiterId = new Guid("d4e3d3b6-44d5-4bdd-bece-4e7e4a21d444"),
                            Status = 3,
                            Title = "HR Business Partner"
                        },
                        new
                        {
                            Id = new Guid("70707070-aaaa-4aaa-bbbb-bbbbbbaaaaaa"),
                            Budget = 100000.0,
                            DepartmentId = new Guid("c3c33333-cccc-4333-cccc-3333c3c3c3c3"),
                            Description = "Venta de software corporativo a clientes grandes en LatAm.",
                            Location = "Remoto - Colombia",
                            RecruiterId = new Guid("e5f4e4a7-55e6-4dee-cafe-5f8f5a32e555"),
                            Status = 1,
                            Title = "Sales Executive B2B"
                        });
                });

            modelBuilder.Entity("Hikru.Position.Backend.Domain.Entities.Recruiter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recruiters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e0a0f3-11a2-4eaa-8bfb-1b4b1f98a111"),
                            Email = "laura.fernandez@hikru.com",
                            Name = "Laura Fernández",
                            Phone = "+51 987 654 321",
                            Seniority = "Senior"
                        },
                        new
                        {
                            Id = new Guid("b2c1b1e4-22b3-4fbb-9cfc-2c5c2f09b222"),
                            Email = "carlos.rojas@hikru.com",
                            Name = "Carlos Rojas",
                            Phone = "+51 984 123 456",
                            Seniority = "Mid"
                        },
                        new
                        {
                            Id = new Guid("c3d2c2f5-33c4-4bcc-adfd-3d6d3a10c333"),
                            Email = "sofia.mendez@hikru.com",
                            Name = "Sofía Méndez",
                            Phone = "+51 982 111 222",
                            Seniority = "Junior"
                        },
                        new
                        {
                            Id = new Guid("d4e3d3b6-44d5-4bdd-bece-4e7e4a21d444"),
                            Email = "jorge.castillo@hikru.com",
                            Name = "Jorge Castillo",
                            Phone = "+51 986 777 888",
                            Seniority = "Senior"
                        },
                        new
                        {
                            Id = new Guid("e5f4e4a7-55e6-4dee-cafe-5f8f5a32e555"),
                            Email = "camila.ruiz@hikru.com",
                            Name = "Camila Ruiz",
                            Phone = "+51 985 222 333",
                            Seniority = "Mid"
                        },
                        new
                        {
                            Id = new Guid("f6f5f5a8-66f7-4aff-dfef-6f9f6a43f666"),
                            Email = "luis.paredes@hikru.com",
                            Name = "Luis Paredes",
                            Phone = "+51 981 444 555",
                            Seniority = "Senior"
                        },
                        new
                        {
                            Id = new Guid("b7f6f6b9-77f8-4bff-bfef-7f0f7a54b777"),
                            Email = "maria.delgado@hikru.com",
                            Name = "María Delgado",
                            Phone = "+51 983 555 666",
                            Seniority = "Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
