# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - hikru-api

on:
  push:
    branches:
      - master
    paths:
      - 'Hikru.Position.Backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Hikru.Position.Backend/Hikru.Position.Backend.sln

      - name: Build
        run: dotnet build Hikru.Position.Backend/Hikru.Position.Backend.sln --configuration Release --no-restore

      - name: Publish API Project
        run: dotnet publish Hikru.Position.Backend/Hikru.Position.Backend.Api/Hikru.Position.Backend.Api.csproj -c Release -o publish

      - name: List publish output (debug)
        run: ls -R publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish
      
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_18A59C2606674F48A1320553431D694C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E20F5F5F0AA4B6F86B12BC6F075C4AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8891ADB3AD649A09309E4A4CBC5019C }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hikru-api'
          slot-name: 'Production'
          package: publish
